=pod

=head1 NAME

named_brtypes_only - ClearCase trigger

Script:        F<named_brtypes_only.pl>

Trigger name:  C<ACC_NAMED_BRTYPES_ONLY>

=head1 SYNOPSIS

Runs as ClearCase trigger script installed on special VOB types ("NovoNordiskDocVOB")

The scripts installs itself correctly when executed outside a trigger context using:

  (ratl)perl named_brtypes_only.pl -install -vob \thevob

To learn the full syntax simply execute the the script without the -vob switch:

  named_brtypes_only -install

=head2 Restrictions

During the install process, that script is supposed to run under the account which owns the VOB.
The script will fail if that is not the case.

An exception is if you execute it in -preview mode

=head1 DESCRIPTION

The triggerscript monitors a list of approved branches and requires that no branches are created except
those listed in the $regexp variable within the script itself. In the version released for NovoNordiskDocVOB
types it only supports "main".

=head2 Bypassing the trigger.

To bypass the script you must create the appropriate semaphore file first
(see the POD documentation for praqma::trigger_helper->enable_semaphore_backdoor).

=head1 AUTHOR

Lars Kruse E<lt>lak@praqma.netE<gt>.

=head1 BUGS

See the website below.

=head1 COPYRIGHT

This program is distributed under the GNU General Pulic License v3.0

Support:    http://launchpad.net/acc

=for html <a href="http://launchpad.net/acc">Project home at Launchpad</a>


=cut
