=pod

=head1 NAME

post_mkbl.pl - A ClearCase trigger script

Script:        F<post_mkbl.pl>

Trigger name:  C<ACC_SET_BL_PLEVEL>

This is an ClearCase UCM trigger script to intended to keep the promotion level
of rootless, composite baselines identical on the same stream.

The trigger fires after the 'chbl' (change baseline) event.

=head1 SYNOPSIS

Runs as ClearCase trigger script installed on UCM project VOBs.

The script installs itself correctly when executed outside a trigger context using:

 ratlperl only_serial_deleviry.pl -install -vob \thevob

To learn the full syntax simply execute the the script without the -vob switch:

 ratlperl only_serial_deleviry.pl -install

=head2 Restrictions

During the install process, that script is supposed to run under the account
which owns the VOB.
The script will fail if that is not the case.

The script will only install the trigger on UCM project vobs.

An exception is if you execute it in -preview mode


=head1 DESCRIPTION

When the promotion level of a rootless, composite baseline component is changed,
the trigger examines the first level dependencies.
The promotion level of depending baselines is changed if the following is true:

=over 4

=item * The dependecy baseline is on the same stream

=item * The dependecy baseline has a different promotion level

=item * The dependecy baseline belongs to a rootless component

=back


If all above is true, that baseline will have it's promotion level changed.
Because we are changing a rootless component's baseline - the trigger fires again
on that change baseline event.



=head1 Features


=head2 Bypassing the trigger.

To bypass the script you must create the appropriate semaphore file first
(see the POD documentation for praqma::trigger_helper->enable_semaphore_backdoor).

It goes without saying, that to avoid misuse of this ability ClearCase administrators should make sure
that triggers are executed - and semaphore files ar looked-up - at locations where common users only
have read access.

=head2 Test suggestions


Please refer to the description at the project wiki page,

=for html <a href="http://wiki.praqma.net/acc/comp/triggers/only_serial_delivery">The trigger's wiki page</a>


=head1 AUTHOR

Jens Brejner, E<lt>jbr@praqma.netE<gt>.

=head1 BUGS

See the website below.

=head1 COPYRIGHT

This program is distributed under the GNU General Pulic License v3.0

Support:    http://launchpad.net/acc

=for html <a href="http://launchpad.net/acc">Project home at Launchpad</a>

=cut
