######################## DOCUMENTATION ##############################

=pod

=head1 NAME

stop_twin - ClearCase trigger

Script:        F<stop_twin.pl>

Trigger name:  C<ACC_STOP_TWIN>

Used as a generic trigger which prevents creation of evil twins in ClearCase - please see the Description

=head1 SYNOPSIS

Runs as ClearCase trigger script installed on any vob, but primaryly on basevobs and ucmvobs ( it less likely to create elements on adminvobs or pvobs).

The scripts installs itself correctly when executed outside a trigger context using:

  (ratl)perl stop_twin -install -vob \thevob

To learn the full syntax simply execute the the script without the -vob switch:

  stop_twin -install

=head2 Restrictions

During the install process, that script is supposed to run under the account which owns the VOB.
The script will fail if that is not the case.

An exception is if you execute it in -preview mode

=head1 DESCRIPTION

In ClearCase all files and directories are elements, and directory elements are versioned just like file elements are.
Every ClearCase element is identfied by an Object ID internally in ClearCase, and these Object ID's each have a name.
Each version of a Directory Element contains a list of file- or directory names which where contained by the directory
element - in that version, and a diff of two versions will display a change in the list of names contained by the directory
element.

In a normal filesystem we delete files - or names - in order to remove them from the directory, but in ClearCase, because the names
actually are names of other elements, we can not accept that an entire element vanishes from Clearcase, just because we don't like or
need the name anymore.
So Clearcase does the only right thing - it removes the name from the directory element version.

Suppose that we at some time after removing the name foo.c from a directory version, ClearCase by itself does not stop us from creating
a brand new element, with the name foo.c, and have that recorded in the directory contents, but what ClearCase has created for us is 2
completely different element, with a history and contents of their own - but they look, by their name - like identical twins.
And they are evil. ClearCase can - and will not - merge what you see as one file, because it is 2 files.

That is the evil twin situation - and this trigger script, prevents the situation from happening, by looking in previous versions of the
directory if the name has been used. If the name have been used, you are not allowed to reuse it.

If you must reuse the name, you will need to merge a directory version that contains the name in question to the
directory version you are working with.

=head2 Case sensivity

By default the trigger operates in Case sensitive mode, so elements with for instance  CamelCase errors can be renamed
without involving the vob owner.

The case sensitive pattern matching can be changed to case insensitive if that is required, to do that, you will edit the
trigger script and change the line

        my $case_sensitive = 1;

to

        my $case_sensitive = 0;

=head2 Bypassing the trigger.

To bypass the script you must create the appropriate semaphore file first
(see the POD documentation for praqma::trigger_helper->enable_semaphore_backdoor).

It goes without saying, that to avoid misuse of this ability ClearCase administrators should make sure
that triggers are executed - and semaphore files ar looked-up - at locations where common users only
have read access.

Trigger script stop_twin.pl respects a local semaphore directory. That means that any user can create the environment varible
with a value of a existing directory.

To utilize this functionality follow these steps.

=over

=item *

Select a directory, and create an User Environment Variable called B<CLEARCASE_USE_LOCAL_SEMAPHORE> and assign it a value of the directory selected.
In the CLI you could do:

=back

 set CLEARCASE_USE_LOCAL_SEMAPHORE=C:\Documents and Settings\student\My Documents\My Pictures

=over

=item *

Then create a file named after the user i.e. "student" in the selected directory

=item *

Edit the file, and add the line stop_twin.pl to it. Close the file.

=item *

Now for the next 4 hours (approximately) C<ACC_STOP_TWIN> will exit silently for without checking for evil twins.

=item *

If more time is required, the semaphore file must be recreated (not copied, delete it and create a new with the same contents.)

=back


=head1 AUTHOR

Jens Brejner, E<lt>jbr@praqma.netE<gt>.

=head1 BUGS

See the website below.

=head1 COPYRIGHT

This program is distributed under the GNU General Pulic License v3.0

Support:    http://launchpad.net/acc

=for html <a href="http://launchpad.net/acc">Project home at Launchpad</a>

=cut
